#
# Copyright (c) 2024, Gluon and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'OpenJDK Static Release'

on:
  push:
    tags:
      - '*'

jobs:
  build-android-linux-aarch64:
    name: android-linux-aarch64
    uses: ./.github/workflows/build-android-linux.yml
    with:
      platform: android-linux-aarch64
      make-target: 'static-libs'
      gcc-major-version: '10'
      debug-levels: '[ "release" ]'

  build-ios-macos-aarch64:
    name: ios-macos-aarch64
    uses: ./.github/workflows/build-ios-macos.yml
    with:
      platform: ios-macos-aarch64
      runs-on: 'macos-14'
      make-target: 'static-libs'
      xcode-toolset-version: '14.3.1'
      debug-levels: '[ "release" ]'

  build-linux-x64:
    name: linux-x64
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-x64
      make-target: 'static-libs'
      gcc-major-version: '10'
      debug-levels: '[ "release" ]'

  build-linux-cross-compile:
    name: linux-cross-compile
    uses: ./.github/workflows/build-cross-compile.yml
    with:
      platform: linux-cross-compile
      make-target: 'static-libs'
      gcc-major-version: '10'
      debug-levels: '[ "release" ]'

  build-macos-x64:
    name: macos-x64
    uses: ./.github/workflows/build-macos.yml
    with:
      platform: macos-x64
      runs-on: 'macos-13'
      make-target: 'static-libs'
      xcode-toolset-version: '14.3.1'
      debug-levels: '[ "release" ]'

  build-macos-aarch64:
    name: macos-aarch64
    uses: ./.github/workflows/build-macos.yml
    with:
      platform: macos-aarch64
      runs-on: 'macos-14'
      make-target: 'static-libs'
      xcode-toolset-version: '14.3.1'
      debug-levels: '[ "release" ]'

  build-windows-x64:
    name: windows-x64
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-x64
      make-target: 'static-libs'
      msvc-toolset-version: '14.29'
      msvc-toolset-architecture: 'x86.x64'
      debug-levels: '[ "release" ]'

  build-windows-aarch64:
    name: windows-aarch64
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-aarch64
      make-target: 'static-libs'
      msvc-toolset-version: '14.29'
      msvc-toolset-architecture: 'arm64'
      extra-conf-options: '--openjdk-target=aarch64-unknown-cygwin'
      debug-levels: '[ "release" ]'

  release:
    needs: [
        build-android-linux-aarch64, build-ios-macos-aarch64,
        build-linux-x64, build-linux-cross-compile,
        build-macos-x64, build-macos-aarch64,
        build-windows-x64, build-windows-aarch64
    ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download Android Linux AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: android-linux-aarch64
          path: ./dist/android-linux-aarch64

      - name: Download iOS macOS AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-macos-aarch64
          path: ./dist/ios-macos-aarch64

      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: ./dist/linux-x64

      - name: Download Linux AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-aarch64
          path: ./dist/linux-aarch64

      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-x64
          path: ./dist/macos-x64

      - name: Download macOS AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64
          path: ./dist/macos-aarch64

      - name: Download Windows x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: ./dist/windows-x64

      - name: Download Windows AArch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-aarch64
          path: ./dist/windows-aarch64

      - name: Check downloaded artifacts
        run: |
          pwd
          ls -R ./dist

      - name: Zip downloaded artifacts
        run: |
          cd ./dist
          zip -r android-linux-aarch64.zip android-linux-aarch64
          zip -r ios-macos-aarch64.zip ios-macos-aarch64
          zip -r linux-x64.zip linux-x64
          zip -r linux-aarch64.zip linux-aarch64
          zip -r macos-x64.zip macos-x64
          zip -r macos-aarch64.zip macos-aarch64
          zip -r windows-x64.zip windows-x64
          zip -r windows-aarch64.zip windows-aarch64

      - name: Check zip files
        run: |
          ls -R ./dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*.zip
